Terminating on signal 15
Traceback (most recent call last):
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 788, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 683, in do_ping
    cursor.execute(self._dialect_specific_select_one)
psycopg2.OperationalError: SSL SYSCALL error: Socket operation on non-socket


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin2/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/admin2/.local/lib/python3.8/site-packages/airflow/__main__.py", line 38, in main
    args.func(args)
  File "/home/admin2/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 51, in command
    return func(*args, **kwargs)
  File "/home/admin2/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "/home/admin2/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 70, in scheduler
    _run_scheduler_job(args=args)
  File "/home/admin2/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 46, in _run_scheduler_job
    job.run()
  File "/home/admin2/.local/lib/python3.8/site-packages/airflow/jobs/base_job.py", line 240, in run
    session.commit()
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1423, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3255, in flush
    self._flush(objects)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3395, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3355, in _flush
    flush_context.execute()
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 453, in execute
    rec.execute(self)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 627, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 209, in save_obj
    for (
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 370, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1709, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 626, in connection
    return self._connection_for_bind(bind, execution_options)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 735, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3144, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2003, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 788, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "/home/admin2/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 683, in do_ping
    cursor.execute(self._dialect_specific_select_one)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: Socket operation on non-socket

(Background on this error at: http://sqlalche.me/e/14/e3q8)
